"use client";

import Link from "next/link";
import { HealthDimensions } from "@/components/features/health-dimensions";
import { NeuralHeader } from "@/components/intelligence/NeuralHeader";
import { useCollection } from "@/components/providers/collection-provider";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Eyebrow } from "@/components/ui/eyebrow";
import { runNeuralCore } from "@/lib/intelligence/intelligence-engine";

export default function TodayPage(){
 const {analysis,owned,logWear,hydrated}=useCollection();
 const intelligence=runNeuralCore({analysis,owned,hydrated});
 const recommendation=intelligence.primaryRecommendation;
 const alternatives=intelligence.alternativeRecommendations;
 const insight=intelligence.collectionIntelligence.priorityInsight;
 const rotation=intelligence.rotationIntelligence;
 const signals=recommendation?.signals.filter(s=>s.id!=="data-quality").slice(0,5)??[];
 return <div className="space-y-6 pb-10">
  <NeuralHeader intelligence={intelligence}/>
  {!hydrated&&<p className="text-sm text-[var(--muted)]">Loading your saved collection…</p>}
  <section className="grid grid-cols-1 gap-5 xl:grid-cols-12">
   <article className="decision-hero relative min-h-[520px] overflow-hidden rounded-[30px] border border-[rgba(214,180,108,.24)] p-6 sm:p-9 xl:col-span-8">
    <div className="pointer-events-none absolute -right-12 -top-20 h-[520px] w-[520px] rounded-full bg-[radial-gradient(circle,rgba(230,168,74,.2),transparent_65%)]"/>
    <div className="relative flex flex-wrap items-start justify-between gap-5"><div><Eyebrow>Today&apos;s decision</Eyebrow><p className="mt-3 text-sm text-[var(--muted)]">Highest-value wear for a 94°F, humid office day</p></div>{recommendation&&<ScoreRing score={recommendation.confidence}/>}</div>
    <div className="relative mt-14 max-w-3xl"><p className="text-[.66rem] font-bold uppercase tracking-[.2em] text-[var(--gold)]">Neural recommendation</p><h2 className="display-serif mt-4 text-5xl leading-[1.02] sm:text-7xl">{recommendation?.fragranceName??"Build your collection"}</h2><p className="mt-6 max-w-2xl text-base leading-8 text-[var(--muted)]">{recommendation?.explanation??"Add your first fragrance to unlock personalized daily intelligence."}</p>{recommendation&&<div className="mt-8 flex flex-wrap gap-8"><MetricInline label="Decision score" value={`${recommendation.score}/100`}/><MetricInline label="Role" value={intelligence.context.desiredRole}/><MetricInline label="Conditions" value={`${intelligence.context.temperatureF}°F · ${intelligence.context.humidity}%`}/></div>}<div className="mt-9 flex flex-wrap gap-3">{recommendation&&<Button variant="primary" onClick={()=>logWear(recommendation.fragranceId)}>Confirm wear</Button>}<Link href="/collection" className="focus-ring inline-flex min-h-12 items-center justify-center rounded-2xl border border-[var(--border)] bg-white/[.035] px-5 text-sm font-semibold transition hover:-translate-y-0.5 hover:border-[rgba(232,200,127,.32)]">Open collection</Link></div></div>
   </article>
   <Card className="xl:col-span-4"><div className="flex items-center justify-between"><Eyebrow>Collection pulse</Eyebrow><span className="rounded-full border border-[var(--border)] px-3 py-1 text-[.64rem] text-[var(--success)]">LIVE</span></div><div className="mt-7 grid grid-cols-2 gap-3"><Metric label="Health" value={intelligence.collectionHealth.score}/><Metric label="Rotation" value={rotation.healthScore}/><Metric label="Fragrances" value={intelligence.collectionIntelligence.collectionSize} suffix=""/><Metric label="Total wears" value={intelligence.collectionIntelligence.totalWears} suffix=""/></div><div className="mt-6 rounded-2xl border border-[var(--border)] bg-black/10 p-4"><p className="font-semibold">{intelligence.collectionHealth.status}</p><p className="mt-2 text-sm leading-6 text-[var(--muted)]">{intelligence.collectionHealth.summary}</p></div></Card>
   <Card className="xl:col-span-8"><div className="flex flex-wrap items-center justify-between gap-4"><div><Eyebrow>Why OLFACTUS chose it</Eyebrow><h3 className="display-serif mt-3 text-3xl">Explainable recommendation signals</h3></div><span className="text-xs text-[var(--muted)]">RE-2.0.0 weighted analysis</span></div><div className="mt-7 grid gap-3 sm:grid-cols-2 xl:grid-cols-5">{signals.map(signal=><div key={signal.id} className="rounded-2xl border border-[var(--border)] bg-[var(--surface-soft)] p-4"><div className="flex items-center justify-between"><p className="text-[.65rem] font-bold uppercase tracking-[.12em] text-[var(--muted)]">{signal.label}</p><strong className="text-sm text-[var(--gold-bright)]">{signal.score}</strong></div><div className="mt-3 h-1 overflow-hidden rounded-full bg-white/[.06]"><span className="block h-full rounded-full bg-[var(--gold)]" style={{width:`${signal.score}%`}}/></div><p className="mt-3 text-xs leading-5 text-[var(--muted)]">{signal.explanation}</p></div>)}</div></Card>
   <Card className="xl:col-span-4"><div className="flex items-start justify-between"><Eyebrow>Rotation monitor</Eyebrow><span className="rounded-full border border-[var(--border)] px-3 py-1 text-[.65rem] uppercase text-[var(--gold)]">{rotation.status}</span></div><div className="mt-6 flex items-end justify-between"><div><p className="display-serif text-6xl text-[var(--gold-bright)]">{rotation.healthScore}</p><p className="mt-1 text-sm text-[var(--muted)]">Rotation health</p></div><p className="text-right text-xs leading-5 text-[var(--muted)]">{rotation.activeRotationSize} active<br/>{rotation.neglected.length} neglected</p></div>{intelligence.rotationAlert&&<div className="mt-6 rounded-2xl border border-[rgba(213,154,69,.24)] bg-[rgba(213,154,69,.06)] p-4"><p className="text-[.64rem] font-bold uppercase tracking-[.14em] text-[var(--warning)]">Priority alert</p><p className="mt-2 font-semibold">{intelligence.rotationAlert.fragranceName}</p><p className="mt-1 text-sm text-[var(--muted)]">Idle for {intelligence.rotationAlert.daysSinceLastWear} days</p></div>}</Card>
   <Card className="xl:col-span-7"><Eyebrow>Priority intelligence</Eyebrow>{insight?<><div className="mt-6 flex items-start justify-between gap-5"><h3 className="display-serif max-w-xl text-4xl leading-tight">{insight.title}</h3><span className="rounded-full border border-[var(--border)] px-3 py-1 text-[.62rem] font-bold uppercase tracking-[.14em] text-[var(--gold)]">{insight.severity}</span></div><p className="mt-4 max-w-2xl leading-7 text-[var(--muted)]">{insight.explanation}</p>{insight.action&&<div className="mt-6 rounded-2xl border border-[rgba(200,168,102,.2)] bg-[rgba(200,168,102,.045)] p-5"><p className="text-[.63rem] font-bold uppercase tracking-[.14em] text-[var(--gold)]">Strategic action</p><p className="mt-2 leading-7">{insight.action}</p></div>}</>:<p className="mt-5 text-[var(--muted)]">Add more collection data to generate strategic insights.</p>}</Card>
   <Card className="xl:col-span-5"><Eyebrow>Alternative decisions</Eyebrow><div className="mt-6 grid gap-3">{alternatives.map((alt,index)=><div key={alt.fragranceId} className="flex items-center justify-between gap-5 rounded-2xl border border-[var(--border)] bg-[var(--surface-soft)] p-4"><div className="flex min-w-0 items-center gap-4"><span className="display-serif text-2xl text-[var(--gold)]">{String(index+1).padStart(2,"0")}</span><div className="min-w-0"><p className="truncate font-semibold">{alt.fragranceName}</p><p className="mt-1 text-xs text-[var(--muted)]">{alt.confidence}% confidence</p></div></div><strong className="text-sm">{alt.score}/100</strong></div>)}</div></Card>
   <Card className="xl:col-span-5"><Eyebrow>Engine status</Eyebrow><div className="mt-6 grid gap-3">{[["Recommendation Engine",intelligence.engineVersions.recommendation],["Collection Intelligence",intelligence.engineVersions.collection],["Rotation Intelligence",intelligence.engineVersions.rotation],["Neural Core",intelligence.engineVersions.neuralCore],["Knowledge Graph","CONNECTED"]].map(([engine,version])=><div key={engine} className="flex items-center justify-between border-b border-[var(--border)] pb-3 last:border-0"><div><p className="text-sm text-[var(--muted)]">{engine}</p><p className="mt-1 text-[.62rem] text-[var(--gold)]">{version}</p></div><span className="flex items-center gap-2 text-xs font-semibold text-[var(--success)]"><span className="h-1.5 w-1.5 rounded-full bg-[var(--success)] shadow-[0_0_8px_rgba(79,166,122,.6)]"/>ACTIVE</span></div>)}</div></Card>
   <Card className="xl:col-span-7"><div className="flex flex-wrap items-center justify-between gap-4"><div><Eyebrow>Collection dimensions</Eyebrow><h3 className="display-serif mt-3 text-3xl">Intelligence health map</h3></div><span className="text-xs text-[var(--muted)]">{intelligence.collectionIntelligence.confidence}% data confidence</span></div><div className="mt-7"><HealthDimensions analysis={analysis}/></div></Card>
  </section>
 </div>
}
function Metric({label,value,suffix="/100"}:{label:string;value:number;suffix?:string}){return <div className="metric-tile rounded-2xl border border-[var(--border)] p-4"><p className="text-[.61rem] font-bold uppercase tracking-[.14em] text-[var(--muted)]">{label}</p><p className="display-serif mt-2 text-3xl">{value}{suffix&&<span className="ml-1 text-[.65rem] text-[var(--muted)]">{suffix}</span>}</p></div>}
function MetricInline({label,value}:{label:string;value:string}){return <div><p className="text-[.62rem] font-bold uppercase tracking-[.14em] text-[var(--muted)]">{label}</p><p className="display-serif mt-1 text-2xl capitalize">{value}</p></div>}
function ScoreRing({score}:{score:number}){const degrees=Math.max(0,Math.min(100,score))*3.6;return <div className="grid h-24 w-24 place-items-center rounded-full p-[1px]" style={{background:`conic-gradient(var(--gold-bright) ${degrees}deg, rgba(255,255,255,.08) 0deg)`}}><div className="grid h-full w-full place-items-center rounded-full bg-[#111419] text-center"><div><p className="display-serif text-2xl text-[var(--gold-bright)]">{score}%</p><p className="text-[.55rem] uppercase tracking-[.12em] text-[var(--muted)]">Confidence</p></div></div></div>}
